### ISSUE TITLE
Offer to be added as maintainer

### ISSUE THREAD

**Issue by ap--** [conda-forge/braceexpand-feedstock#7]
Hi @cbrueffer,

The current conda-forge package of braceexpand is causing issues in conda-forge/webdataset-feedstock#33 due to stricter wheel metadata parsing of `pip==22.4`.

I'd be happy to help fix this here, and am volunteering to be added as a maintainer.

Cheers,
Andreas 😃

**Comment by cbrueffer** [comment]
Hi Andreas, thanks for the offer, I'm glad to add you and the bot should open a PR for this soon. This package was a dependency for something else I needed back then, so it has definitely been neglected.

**Comment by cbrueffer** [comment]
I merged https://github.com/conda-forge/braceexpand-feedstock/pull/9; there were CI errors with it, but the changes looked alright and Github thinks the `CODEOWNERS` file looks fine after the merge. Let me know if you run into problems.

**Comment by ap--** [comment]
Thanks for the quick response! I'll release the newest version later today then.

> This package was a dependency for something else I needed back then

Same here.

Have a great weekend,
Andreas
